### ISSUE TITLE
Vestigial demo link in readme

### ISSUE THREAD

**Issue by rdela** [lumeland/theme-simple-blog#30]
I think this link should be to `./src` now instread of `./demo`?

```md
You can see an example in the [demo](./demo) folder. To customize it copy the
```

https://github.com/lumeland/theme-simple-blog/blob/fe1d3101946b300436504e9d38357c2fd3d80666/README.md?plain=1#L28

Probably should have been updated with the [0.15.0](https://github.com/lumeland/theme-simple-blog/blob/v0.15.0/CHANGELOG.md) - 2024-03-19 release.

```md
### Removed
- `/demo` folder.
```

https://github.com/lumeland/theme-simple-blog/blob/fe1d3101946b300436504e9d38357c2fd3d80666/CHANGELOG.md?plain=1#L57-L58

I will make the PR if you want but wanted to make sure `src` is what you want there, and give you an option to reword it however you like first.

**Comment by rdela** [comment]
Adding a quick note so I don’t forget, `/demo` gets mentioned again at the end of the readme: 

> And you can remove the `/demo` folder.

**Comment by rdela** [comment]
Also if we are going to update the readme might as well make this line import 0.15.5 instead of 0.10.2 no?

```
import blog from "https://deno.land/x/lume_theme_simple_blog@v0.10.2/mod.ts";
```

**Comment by oscarotero** [comment]
Yep, the `demo` folder was removed because the theme can be configured with the init command of lume (https://lume.land/theme/simple-blog/), so no need to demonstrate how to import it. Running `deno run -A https://lume.land/init.ts --theme=simple-blog` will create a new project with simple-blog configured.

Thanks for bringing this up. Feel free to work on a PR to remove this mention (and even change the text to mention the correct way to initialize it).

**Comment by rdela** [comment]
Great I will add a PR now
